### ISSUE TITLE
Feature request - get-info :time

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/cvc4-projects#102]
As a user of cvc4 I am often comparing different alternatives for their performance.
Since cvc4 misses a command to report the system time, I have to use external time measurements like PowerShell's `Measure-Command`. 
These external measurements are influence by caching effects and parsing times and prevent me from focusing on the statements under investigation.
I tried using `echo` to measure progress, but to limited success.
I would really like a command like `(get-info :time)` that provides me with the system time (or some microseconds since the start) for time measurements.
Could this be added?

**Comment by nafur** [comment]
Unfortunately, there is no easy way to extract a single statistic from the system (and thus allow for a generic way to query statistics via `(get-info ...)`.
If you use CVC4 via its API, you can call `SmtEngine::getTimeUsage()` which should pretty much do what you asked for.

**Comment by nafur** [comment]
After some discussion, we figured there are two possibilities that we could do (possibly both):
1. `(get-info :time)` could return the current system time (essentially `std::chrono::system_clock::now()`) so you can query it whenever you want and compute the difference.
2. Allow for `(get-info :<stat>)` where `<stat>` is an arbitrary statistic. This would be a linear search over all statistics, but there should not be too many of them anyways.

Which of those would you prefer, or do you see use cases for both of them?

**Comment by pjljvandelaar** [comment]
I will be happy with the first. 
We can always extend later.

P.s. is elapsed cpu time available on all platforms cvc4 supports? If so, I would prefer that time measurement over the current system time.

**Comment by nafur** [comment]
Elapsed CPU time could be available on all platforms (that properly implement the C++ standard, our timer relies on `std::chrono`). However, this timer would need to live somewhere, and it is not really clear to me where this would be.

I'd prefer to give you the system time (via the very same mechanism of obtaining it, `std::chrono`) as it is stateless. After all, it is the same, only the epoch changes (i.e. what zero means: start of the binary vs. 1970).

Giving the time since starting the binary in a stateless manner may be possible, but I've not seen a portable way yet and would thus like to avoid it.

**Comment by pjljvandelaar** [comment]
I think I wasn't clear: I meant with elapsed cpu time, the time cvc4 has gotten on the cpu- the used clock cycles. Since, the interleaving of cvc4 with other programs changes the elapsed real time, but not the elapsed/consumed cpu time/cycles.
Hopes this clarifies my earlier question.

**Comment by nafur** [comment]
I just added a PR that provides `:time` and returns the used clock cycles (as per `std::clock()`). I still think querying individual statistics would be useful, but I found a few unexpected obstacles (for example SMTLIB only allows `(get-info :<simple_symbol>)` where `simple_symbol` can not contain `:`, which is a problem with how we name statistics).

**Comment by martin-cs** [comment]
@pjljvandelaar @nafur can I be unhelpful for a bit and say I don't think this is a good idea for anyone involved:

On the user side I would *strongly* suggest that you use an external script for measuring the resources used.  Although I have absolute faith in @nafur and in the rest of the team that this would not happen, I have seen cases where tools incorrectly reported their resource usage.  There are also a number of subtleties in accounting for time and resource so these are best done outside of a tool using the operating system's information directly.

On the developer side I would say that having the output of a solver be deterministic and cross-platform deterministic is incredibly valuable and not the kind of thing we should just throw away.

Sorry to be negative but ...

**Comment by pjljvandelaar** [comment]
@martin-cs I disagree: limiting time measuring to external scripts forces
1. different scripts on different operating systems. 
2. Splitting scripts into different parts: e.g. initialization and 'to be measured' part. These parts and the call to the os should be called by the measurement script. This creates a lot of unnecessary complexity.

**Comment by nafur** [comment]
Thanks for the feedback @martin-cs.
Indeed, I'd strongly agree that for benchmarking people should not use this mechanism: not only would it be hard to check that we don't cheat (though, of course, we don't :smile: ), but also might be hard to include parsing time or startup time, etc.
However, it can still be very useful to analyze specific parts of the solving process, and it is a very small piece of code to maintain.
As for determinism: I agree in general, but just don't do `(get-info :time)` then... :wink:

**Comment by martin-cs** [comment]
OK.

@pjljvandelaar may I suggest the Olivier Roussel's runsolver http://www.cril.univ-artois.fr/~roussel/rech.php?lang=eng . I believe this is what the SAT and SMT competitions use.
