### ISSUE TITLE
tlimit does not limit the entire run in incremental mode

### ISSUE THREAD

**Issue by daniel-larraz** [CVC4/cvc4-projects#202]
According to CVC4 user manual, the `--tlimit` command line option in CVC4 limits the entire runtime of CVC4. However, this does not seem to be the case when the `--incremental` option is also used. See attached problem ([tlimit-inc.txt](https://github.com/CVC4/CVC4/files/4677881/tlimit-inc.txt)) and command line arguments below. Every `check-sat-assuming` command takes less than 1s on my machine, so cvc4 does not timeout. 

**Command line arguments**: `cvc4 --lang smt2 --incremental --tlimit=1000 tlimit-inc.txt`
**CVC4 version/commit**: 08a178c7
**Operating system**: Ubuntu 18.04

**Comment by nafur** [comment]
This issue should be fixed with https://github.com/CVC4/CVC4/commit/a0a389a1f7c16b6a1fb56b3ce8ee519cf5717f04 which completely reimplemented the handling of `--tlimit`. Please reopen this ticket, if you still have issues with `--tlimit`.
