### ISSUE TITLE
Performance issue on QF_NRA formulas

### ISSUE THREAD

**Issue by rainoftime** [CVC4/cvc4-projects#240]
Hi, for the following formula 
~~~~
(set-logic QF_NRA)
(declare-fun _substvar_45_ () Real)
(declare-const r0 Real)
(declare-const r2 Real)
(assert (> (/ (+ 758.33 r2 r2 r0) _substvar_45_) 9183098.0 r2))
(check-sat)
~~~~
CVC4 nightly https://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-08-18-x86_64-linux-opt
~~~~
time ./yices_smt2 xx.smt2
sat
real    0m0.007s
user    0m0.002s
sys     0m0.005s

time ./z3 xx.smt2                                                                                                                     
sat
real    0m0.006s
user    0m0.004s
sys     0m0.003s

./cvc4 --tlimit=30000 xx.smt2                                                                                                                        
CVC4 interrupted by timeout.

**Comment by nafur** [comment]
> $ time bin/cvc4 cur.smt2 
> sat
> 
> real	0m0,013s
> user	0m0,003s
> sys	0m0,010s
> $ time bin/cvc4 --force-logic=ALL cur.smt2 
> sat
> 
> real	0m0,013s
> user	0m0,008s
> sys	0m0,005s
> $ time bin/cvc4 --force-logic=QF_NRA cur.smt2 
> sat
> 
> real	0m0,013s
> user	0m0,004s
> sys	0m0,009s

We now solve this instantly as well, probably since we use the CAD solver by default. (same for the second example)
