### ISSUE TITLE
Solver hangs on NRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/cvc4-projects#49]
Hi,

For this NRA formula:
```
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(declare-fun d () Int)
(declare-fun e () Int)
(declare-fun f () Int)
(assert (or (= d b) (= (/ a (/ c e)) 0)))
(assert (= (/ c f) (+ (/ a f) 1)))
(assert (not (= 0 (/ c f))))
(check-sat)
```
CVC4 will hang on it, while z3 give `sat` result in a second.

Command: `cvc4 file.smt2`
OS: Ubuntu 18.04
Revision: ed8f4388c859595178e303f65393105e99d4eb59

**Comment by nafur** [comment]
The current master solves this example instantly:
> $ time bin/cvc4 ../../cvc4/build/test.smt2 
> sat
> 
> real	0m0,026s
> user	0m0,025s
> sys	0m0,000s

I thus close this issue. Please reopen it or open a new issue if you still experience this (or similar) issues.
